import { FormEvent, useCallback, useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { ArrowLeft, Loader2, MessageCircle, Plus, Send, Users } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/useAuth";
import { useToast } from "@/hooks/use-toast";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";

type Post={id:string;user_id:string;title:string;content:string;category:string;created_at:string|null;comments_count:number|null};
type Comment={id:string;post_id:string;user_id:string;content:string;created_at:string|null};
const categories=["Student Finances","Business Owners","NYSC","Side Hustles","Saving","Investing"];

const Community=()=>{
 const {user}=useAuth(); const navigate=useNavigate(); const {toast}=useToast();
 const [posts,setPosts]=useState<Post[]>([]); const [comments,setComments]=useState<Comment[]>([]); const [selected,setSelected]=useState<Post|null>(null); const [loading,setLoading]=useState(true);
 const [title,setTitle]=useState(""); const [content,setContent]=useState(""); const [category,setCategory]=useState(categories[0]); const [reply,setReply]=useState(""); const [open,setOpen]=useState(false);
 const load=useCallback(async()=>{setLoading(true); const [p,c]=await Promise.all([supabase.from("community_posts").select("id,user_id,title,content,category,created_at,comments_count").order("created_at",{ascending:false}).limit(50),supabase.from("community_comments").select("id,post_id,user_id,content,created_at").order("created_at",{ascending:true})]); if(p.error||c.error) toast({title:"Community could not be loaded",description:(p.error||c.error)?.message,variant:"destructive"}); setPosts((p.data||[]) as Post[]); setComments((c.data||[]) as Comment[]); setLoading(false)},[toast]);
 useEffect(()=>{void load()},[load]);
 const createPost=async(e:FormEvent)=>{e.preventDefault(); if(!user)return; const {error}=await supabase.from("community_posts").insert({user_id:user.id,title:title.trim(),content:content.trim(),category}); if(error)return toast({title:"Post not published",description:error.message,variant:"destructive"}); setTitle("");setContent("");setOpen(false);toast({title:"Post published"});void load()};
 const createComment=async(e:FormEvent)=>{e.preventDefault();if(!user||!selected)return;const {error}=await supabase.from("community_comments").insert({post_id:selected.id,user_id:user.id,content:reply.trim()});if(error)return toast({title:"Reply not published",description:error.message,variant:"destructive"});setReply("");toast({title:"Reply published"});void load()};
 return <div className="min-h-screen bg-slate-50"><header className="border-b bg-white"><div className="mx-auto flex max-w-5xl items-center justify-between px-4 py-4"><strong>MyFinance Community</strong><Button variant="outline" onClick={()=>navigate("/dashboard")}><ArrowLeft className="mr-2 h-4 w-4"/>Dashboard</Button></div></header><main className="mx-auto max-w-5xl px-4 py-10"><div className="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="flex items-center gap-2 font-medium text-emerald-700"><Users className="h-4 w-4"/>Learn together</p><h1 className="mt-1 text-3xl font-bold">Community forum</h1><p className="mt-2 text-slate-600">Share practical experiences. Never post account numbers or other sensitive information.</p></div><Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button className="bg-emerald-700 hover:bg-emerald-800"><Plus className="mr-2 h-4 w-4"/>New post</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Start a discussion</DialogTitle></DialogHeader><form className="space-y-4" onSubmit={createPost}><div className="space-y-2"><Label>Topic</Label><Input value={title} onChange={e=>setTitle(e.target.value)} required maxLength={120}/></div><div className="space-y-2"><Label>Group</Label><Select value={category} onValueChange={setCategory}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{categories.map(c=><SelectItem key={c} value={c}>{c}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label>Post</Label><Textarea value={content} onChange={e=>setContent(e.target.value)} required maxLength={2000}/></div><Button className="w-full bg-emerald-700">Publish</Button></form></DialogContent></Dialog></div>
 {loading?<div className="flex justify-center py-16"><Loader2 className="h-7 w-7 animate-spin text-emerald-700"/></div>:posts.length===0?<Card><CardContent className="py-16 text-center text-slate-500">No discussions yet. Start the first one.</CardContent></Card>:<div className="grid gap-5">{posts.map(post=>{const count=comments.filter(c=>c.post_id===post.id).length;return <Card key={post.id}><CardHeader><div className="flex items-center justify-between gap-3"><Badge variant="outline">{post.category}</Badge><span className="text-xs text-slate-400">{post.created_at?new Date(post.created_at).toLocaleDateString("en-NG"):""}</span></div><CardTitle>{post.title}</CardTitle><CardDescription>Community member</CardDescription></CardHeader><CardContent><p className="whitespace-pre-wrap leading-7 text-slate-700">{post.content}</p><Button variant="ghost" className="mt-3 px-0 text-emerald-700" onClick={()=>setSelected(post)}><MessageCircle className="mr-2 h-4 w-4"/>{count} {count===1?"reply":"replies"}</Button></CardContent></Card>})}</div>}
 <Dialog open={Boolean(selected)} onOpenChange={v=>!v&&setSelected(null)}><DialogContent className="max-h-[80vh] overflow-y-auto"><DialogHeader><DialogTitle>{selected?.title}</DialogTitle></DialogHeader><div className="space-y-3">{comments.filter(c=>c.post_id===selected?.id).map(c=><div key={c.id} className="rounded-lg bg-slate-100 p-3"><p className="text-sm leading-6">{c.content}</p><p className="mt-1 text-xs text-slate-400">Community member · {c.created_at?new Date(c.created_at).toLocaleDateString("en-NG"):""}</p></div>)}</div><form className="flex gap-2" onSubmit={createComment}><Input placeholder="Write a helpful reply" value={reply} onChange={e=>setReply(e.target.value)} required maxLength={1000}/><Button size="icon" className="shrink-0 bg-emerald-700" aria-label="Send reply"><Send className="h-4 w-4"/></Button></form></DialogContent></Dialog>
 </main></div>
};
export default Community;
