import { useEffect, useMemo, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { ArrowLeft, CheckCircle2, ChevronRight, Clock3, Crown, LockKeyhole, ShieldAlert } from "lucide-react";
import { courses, findLesson, Lesson } from "@/data/courses";
import { useAuth } from "@/hooks/useAuth";
import { usePremiumAccess } from "@/hooks/usePremiumAccess";
import { useToast } from "@/hooks/use-toast";
import { supabase } from "@/integrations/supabase/client";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

const CoursePage=()=>{const {courseSlug,lessonSlug}=useParams();const navigate=useNavigate();const {user}=useAuth();const {isPremium,loading}=usePremiumAccess();const {toast}=useToast();const course=courses.find(c=>c.slug===courseSlug);const first=course?.modules[0]?.lessons[0];const active=lessonSlug?findLesson(courseSlug||"",lessonSlug):first?findLesson(courseSlug||"",first.slug):null;const [selected,setSelected]=useState<number|null>(null);const [completed,setCompleted]=useState<Set<string>>(new Set());
 useEffect(()=>{setSelected(null)},[lessonSlug]);useEffect(()=>{if(!user||!courseSlug)return;void supabase.from("course_progress").select("lesson_slug").eq("user_id",user.id).eq("course_slug",courseSlug).eq("completed",true).then(({data})=>setCompleted(new Set((data||[]).map(r=>r.lesson_slug))))},[courseSlug,user]);
 const permitted=useMemo(()=>!!active&&(!course?.premium||isPremium||active.lesson.preview),[active,course?.premium,isPremium]);
 if(!course||!active)return <div className="min-h-screen grid place-items-center"><Card><CardContent className="p-8 text-center"><p>Course or lesson not found.</p><Button className="mt-4" onClick={()=>navigate('/learn')}>Back to Academy</Button></CardContent></Card></div>;
 const markComplete=async()=>{if(!user)return navigate('/auth');const {error}=await supabase.from("course_progress").upsert({user_id:user.id,course_slug:course.slug,lesson_slug:active.lesson.slug,completed:true,completed_at:new Date().toISOString()},{onConflict:"user_id,course_slug,lesson_slug"});if(error)return toast({title:"Progress was not saved",description:error.message,variant:"destructive"});setCompleted(new Set([...completed,active.lesson.slug]));toast({title:"Lesson completed",description:"Your progress has been saved."})};
 return <div className="min-h-screen bg-slate-50"><header className="sticky top-0 z-20 border-b bg-white/95"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-4"><Button variant="ghost" onClick={()=>navigate('/learn')}><ArrowLeft className="mr-2 h-4 w-4"/>Academy</Button><Button variant="outline" onClick={()=>navigate('/premium')}><Crown className="mr-2 h-4 w-4 text-amber-600"/>Premium</Button></div></header><main className="mx-auto grid max-w-7xl gap-6 px-4 py-8 lg:grid-cols-[340px_1fr]"><aside><Card className="lg:sticky lg:top-24"><CardHeader><Badge className="w-fit" variant="outline">{course.level}</Badge><CardTitle>{course.title}</CardTitle><p className="text-sm text-slate-500">{course.subtitle}</p></CardHeader><CardContent className="space-y-5">{course.modules.map(module=><div key={module.title}><p className="mb-2 text-xs font-bold uppercase tracking-wide text-emerald-700">{module.title}</p>{module.lessons.map(lesson=>{const locked=course.premium&&!isPremium&&!lesson.preview;return <button key={lesson.slug} onClick={()=>navigate(`/courses/${course.slug}/${lesson.slug}`)} className={`mb-1 flex w-full items-center gap-2 rounded-lg p-3 text-left text-sm ${lesson.slug===active.lesson.slug?'bg-emerald-100 text-emerald-950':'hover:bg-slate-100'}`}>{completed.has(lesson.slug)?<CheckCircle2 className="h-4 w-4 text-emerald-700"/>:locked?<LockKeyhole className="h-4 w-4 text-amber-700"/>:<ChevronRight className="h-4 w-4"/>}<span className="flex-1">{lesson.title}</span>{lesson.preview&&<Badge variant="outline">Preview</Badge>}</button>})}</div>)}</CardContent></Card></aside><section>{loading?<Card><CardContent className="p-12">Checking access…</CardContent></Card>:permitted?<LessonView lesson={active.lesson} selected={selected} setSelected={setSelected} completed={completed.has(active.lesson.slug)} markComplete={markComplete}/>:<Locked title={active.lesson.title} goPremium={()=>navigate('/premium')}/>}</section></main></div>};

const LessonView=({lesson,selected,setSelected,completed,markComplete}:{lesson:Lesson;selected:number|null;setSelected:(n:number)=>void;completed:boolean;markComplete:()=>void})=><div className="space-y-6"><div><div className="mb-3 flex items-center gap-3"><Badge variant="outline"><Clock3 className="mr-1 h-3 w-3"/>{lesson.duration} min</Badge>{lesson.preview&&<Badge className="bg-emerald-100 text-emerald-800">Free preview</Badge>}</div><h1 className="text-4xl font-bold text-slate-950">{lesson.title}</h1><p className="mt-4 text-lg leading-8 text-slate-600">{lesson.overview}</p></div><Card><CardHeader><CardTitle>By the end, you can</CardTitle></CardHeader><CardContent className="space-y-2">{lesson.outcomes.map(x=><p className="flex gap-2" key={x}><CheckCircle2 className="mt-1 h-4 w-4 text-emerald-700"/>{x}</p>)}</CardContent></Card>{lesson.concepts.map(x=><Card key={x.title}><CardHeader><CardTitle>{x.title}</CardTitle></CardHeader><CardContent><p className="leading-7 text-slate-700">{x.body}</p></CardContent></Card>)}<Card><CardHeader><CardTitle>Put it into practice</CardTitle></CardHeader><CardContent><ol className="list-decimal space-y-3 pl-5">{lesson.actionSteps.map(x=><li key={x}>{x}</li>)}</ol></CardContent></Card><Card className="border-emerald-200"><CardHeader><CardTitle>Knowledge check</CardTitle><p>{lesson.quiz.question}</p></CardHeader><CardContent className="space-y-3">{lesson.quiz.options.map((x,i)=><Button key={x} variant={selected===i?'default':'outline'} className="h-auto w-full justify-start whitespace-normal py-3 text-left" onClick={()=>setSelected(i)}>{x}</Button>)}{selected!==null&&<div className={`rounded-lg p-4 text-sm ${selected===lesson.quiz.answer?'bg-emerald-50 text-emerald-900':'bg-amber-50 text-amber-950'}`}><strong>{selected===lesson.quiz.answer?'Correct.':'Not quite.'}</strong> {lesson.quiz.explanation}</div>}<Button disabled={selected!==lesson.quiz.answer||completed} className="w-full bg-emerald-700" onClick={markComplete}>{completed?'Completed':'Mark lesson complete'}</Button></CardContent></Card><p className="flex gap-2 rounded-lg bg-slate-100 p-4 text-xs leading-5 text-slate-600"><ShieldAlert className="h-4 w-4 shrink-0"/>Educational content only. Product terms, market conditions and regulations change. Verify current information with official sources and licensed providers before acting.</p></div>;

const Locked=({title,goPremium}:{title:string;goPremium:()=>void})=><Card className="border-amber-200"><CardContent className="p-10 text-center"><LockKeyhole className="mx-auto h-12 w-12 text-amber-600"/><h1 className="mt-5 text-3xl font-bold">{title}</h1><p className="mx-auto mt-3 max-w-xl text-slate-600">This lesson is part of MyFinance Premium. Upgrade to unlock the full curriculum, quizzes and saved learning progress.</p><Button className="mt-6 bg-emerald-700" onClick={goPremium}><Crown className="mr-2 h-4 w-4"/>View Premium</Button></CardContent></Card>;
export default CoursePage;
