import { useMemo } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";
import { ArrowLeft, BookOpen, CheckCircle2, ShieldAlert } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";

const lessons = {
  "treasury-bills": { title:"Treasury Bills", level:"Beginner", summary:"Short-term debt issued by the Federal Government of Nigeria and sold at a discount.", points:["Understand tenor, discount rate and maturity value before committing funds.","Use only SEC-regulated brokers, banks or licensed investment platforms.","Compare the effective yield after fees and taxes—not promotional headline rates.","Match the maturity date to when you expect to need the money."] },
  "mutual-funds": { title:"Mutual Funds", level:"Beginner", summary:"Pooled portfolios managed by professionals across money-market, bond, balanced and equity strategies.", points:["Read the fund fact sheet and confirm the manager is regulated.","Compare asset mix, fees, historical volatility and withdrawal terms.","Returns are not guaranteed; choose a risk level that fits your time horizon.","Diversification reduces concentration risk but does not remove market risk."] },
  agritech: { title:"AgricTech Investments", level:"Intermediate", summary:"Agriculture-linked opportunities can support production but may carry operational, weather and liquidity risks.", points:["Verify the company, product registration and underlying business model.","Do not treat fixed-return marketing as a guarantee.","Check insurance, custody, exit terms and what happens when a project fails.","Keep high-risk opportunities to a small portion of a diversified portfolio."] },
  "money-mistakes": { title:"Money Mistakes to Avoid in Your 20s", level:"Premium preview", summary:"Build resilient habits before chasing returns.", points:["Track cash flow before increasing lifestyle commitments.","Build an emergency buffer and avoid expensive consumer debt.","Start investing early, consistently and within your risk capacity.","Protect your accounts and ignore pressure-based investment offers."] },
  "wealth-9-to-5": { title:"Build Wealth with a 9–5", level:"Premium preview", summary:"Turn stable income into a repeatable wealth-building system.", points:["Automate saving immediately after payday.","Direct raises toward goals before lifestyle inflation absorbs them.","Develop valuable skills and a responsible secondary income stream.","Review your plan quarterly and rebalance priorities."] },
  "debt-free": { title:"Debt-Free Living in Africa", level:"Free", summary:"Organise debt and choose a repayment strategy you can sustain.", points:["List every balance, interest rate, fee and minimum payment.","Keep minimums current, then target either the highest rate or smallest balance.","Contact regulated lenders early if repayment becomes difficult.","Avoid borrowing to invest or repay unverified digital lenders."] },
  "start-investing": { title:"Start Investing with ₦5,000", level:"Free", summary:"Small, regular contributions can establish the habit before your income grows.", points:["Build a starter emergency buffer first.","Choose a regulated, diversified product with transparent fees.","Automate a modest amount you can leave invested.","Increase contributions as your income and knowledge improve."] },
  "capital-market": { title:"Understanding Nigeria’s Capital Market", level:"Free", summary:"Learn how securities are issued, traded and regulated.", points:["The SEC regulates the market while NGX facilitates securities trading.","Stocks, bonds, collective investment schemes and government securities behave differently.","Use licensed operators and verify them independently.","Past performance is not a promise of future returns."] },
} as const;

const Education = () => {
  const navigate=useNavigate(); const [params]=useSearchParams();
  const lesson=useMemo(()=>lessons[(params.get("lesson")||"treasury-bills") as keyof typeof lessons]||lessons["treasury-bills"],[params]);
  return <div className="min-h-screen bg-slate-50"><header className="border-b bg-white"><div className="mx-auto flex max-w-4xl items-center justify-between px-4 py-4"><strong>MyFinance Learning</strong><Button variant="outline" onClick={()=>navigate(-1)}><ArrowLeft className="mr-2 h-4 w-4"/>Back</Button></div></header><main className="mx-auto max-w-4xl px-4 py-10"><Badge className="mb-4 bg-emerald-100 text-emerald-800 hover:bg-emerald-100">{lesson.level}</Badge><h1 className="text-4xl font-bold text-slate-950">{lesson.title}</h1><p className="mt-4 text-lg leading-8 text-slate-600">{lesson.summary}</p><Card className="mt-8"><CardHeader><CardTitle className="flex items-center gap-2"><BookOpen className="h-5 w-5 text-emerald-700"/>What to know</CardTitle><CardDescription>A practical starting checklist.</CardDescription></CardHeader><CardContent className="space-y-4">{lesson.points.map(point=><div key={point} className="flex gap-3"><CheckCircle2 className="mt-0.5 h-5 w-5 shrink-0 text-emerald-700"/><p className="leading-7 text-slate-700">{point}</p></div>)}</CardContent></Card><div className="mt-8 flex gap-3 rounded-xl border border-amber-200 bg-amber-50 p-5"><ShieldAlert className="mt-1 h-5 w-5 shrink-0 text-amber-700"/><p className="text-sm leading-6 text-amber-950">Educational content only. Verify providers with the appropriate regulator and consider qualified advice before making significant financial decisions.</p></div></main></div>;
};

export default Education;
