import { useCallback, useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { ArrowLeft, BookOpen, CheckCircle2, Clock3, Crown, LockKeyhole, Route, ShieldCheck } from "lucide-react";
import { courses, courseLessonCount } from "@/data/courses";
import { useAuth } from "@/hooks/useAuth";
import { usePremiumAccess } from "@/hooks/usePremiumAccess";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";

const Education=()=>{const navigate=useNavigate();const {user}=useAuth();const {isPremium}=usePremiumAccess();const [completed,setCompleted]=useState<Record<string,number>>({});
 const load=useCallback(async()=>{if(!user)return;const {data}=await supabase.from("course_progress").select("course_slug,lesson_slug").eq("user_id",user.id).eq("completed",true);const map:Record<string,Set<string>>={};for(const row of data||[])(map[row.course_slug]??=new Set()).add(row.lesson_slug);setCompleted(Object.fromEntries(Object.entries(map).map(([k,v])=>[k,v.size])))},[user]);useEffect(()=>{void load()},[load]);
 const total=useMemo(()=>courses.reduce((s,c)=>s+courseLessonCount(c),0),[]);const done=Object.values(completed).reduce((s,n)=>s+n,0);
 return <div className="min-h-screen bg-slate-50"><header className="sticky top-0 z-20 border-b bg-white/95 backdrop-blur"><div className="mx-auto flex max-w-6xl items-center justify-between px-4 py-4"><div><strong className="block">MyFinance Academy</strong><span className="text-xs text-slate-500">by Finance Wise</span></div><div className="flex gap-2"><Button variant="ghost" onClick={()=>navigate("/premium")}><Crown className="mr-2 h-4 w-4 text-amber-600"/>Premium</Button><Button variant="outline" onClick={()=>navigate(user?"/dashboard":"/")}><ArrowLeft className="mr-2 h-4 w-4"/>{user?"Dashboard":"Home"}</Button></div></div></header>
 <main><section className="bg-gradient-to-br from-emerald-950 via-emerald-900 to-slate-950 text-white"><div className="mx-auto max-w-6xl px-4 py-16"><Badge className="mb-5 border-white/20 bg-white/10 text-white">Practical African financial education</Badge><h1 className="max-w-4xl text-4xl font-bold leading-tight md:text-6xl">Learn to make financial decisions—not just memorise definitions.</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-emerald-100">Structured courses, Nigeria-focused examples, decision frameworks, quizzes and action exercises. Product information is educational and never presented as a guaranteed return.</p><div className="mt-8 grid max-w-2xl grid-cols-3 gap-4"><Stat value={String(courses.length)} label="courses"/><Stat value={String(total)} label="lessons"/><Stat value="15+" label="hours"/></div></div></section>
 <section className="mx-auto max-w-6xl px-4 py-12">{user&&<Card className="mb-8 border-emerald-200 bg-emerald-50"><CardContent className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center"><Route className="h-8 w-8 text-emerald-700"/><div className="flex-1"><p className="font-bold text-emerald-950">Your learning journey</p><p className="text-sm text-emerald-800">{done} of {total} lessons completed</p></div><Progress className="sm:w-64" value={(done/total)*100}/></CardContent></Card>}
 <div className="mb-7"><p className="font-medium text-emerald-700">Structured curriculum</p><h2 className="text-3xl font-bold">Choose your learning path</h2></div><div className="grid gap-6 lg:grid-cols-2">{courses.map(course=>{const count=courseLessonCount(course),canAccess=!course.premium||isPremium;return <Card key={course.slug} className="overflow-hidden transition-shadow hover:shadow-lg"><CardHeader className="border-b bg-white"><div className="mb-2 flex items-center justify-between"><Badge variant="outline">{course.level}</Badge>{course.premium?<Badge className="bg-amber-100 text-amber-900 hover:bg-amber-100"><Crown className="mr-1 h-3 w-3"/>Premium</Badge>:<Badge className="bg-emerald-100 text-emerald-800 hover:bg-emerald-100">Free</Badge>}</div><CardTitle className="text-2xl">{course.title}</CardTitle><CardDescription className="text-base leading-6">{course.subtitle}</CardDescription></CardHeader><CardContent className="space-y-5 p-6"><div className="flex gap-5 text-sm text-slate-500"><span className="flex items-center gap-1"><BookOpen className="h-4 w-4"/>{count} lessons</span><span className="flex items-center gap-1"><Clock3 className="h-4 w-4"/>{course.duration}</span></div><p className="text-sm leading-6 text-slate-600"><strong>Best for:</strong> {course.audience}</p><div className="space-y-2">{course.outcomes.slice(0,3).map(v=><p key={v} className="flex gap-2 text-sm"><CheckCircle2 className="h-4 w-4 shrink-0 text-emerald-700"/>{v}</p>)}</div>{user&&<div><div className="mb-1 flex justify-between text-xs text-slate-500"><span>Progress</span><span>{completed[course.slug]||0}/{count}</span></div><Progress value={((completed[course.slug]||0)/count)*100}/></div>}<Button className="w-full bg-emerald-700 hover:bg-emerald-800" onClick={()=>navigate(`/courses/${course.slug}`)}>{canAccess?"View course":<><LockKeyhole className="mr-2 h-4 w-4"/>Preview course</>}</Button></CardContent></Card>})}</div>
 <div className="mt-10 flex gap-3 rounded-xl border border-amber-200 bg-amber-50 p-5"><ShieldCheck className="h-6 w-6 shrink-0 text-amber-700"/><p className="text-sm leading-6 text-amber-950"><strong>Education, not a recommendation.</strong> MyFinance explains products and decision frameworks. It does not recommend a specific security, provider or guaranteed return. Verify current terms with official regulators and licensed operators.</p></div></section></main></div>};
const Stat=({value,label}:{value:string;label:string})=><div><p className="text-3xl font-bold">{value}</p><p className="text-sm text-emerald-200">{label}</p></div>;
export default Education;
