import { useNavigate, useParams } from "react-router-dom";
import { ArrowLeft } from "lucide-react";
import { Button } from "@/components/ui/button";

const content = {
  privacy:{title:"Privacy Policy",intro:"MyFinance uses your information to provide budgeting, savings, assessment and support features.",sections:[["Information we process","Account details, profile information, financial records you enter, assessment responses and support requests."],["How it is used","To operate your account, calculate summaries, personalize educational guidance, protect the service and respond to support."],["Your control","You may update your profile and remove individual transaction records. Contact Finance Wise for account or privacy requests."],["Security","Account-linked records are protected with authenticated access and database row-level security. No system can guarantee absolute security."]]},
  terms:{title:"Terms of Service",intro:"These terms govern your use of the MyFinance educational money-management service.",sections:[["Educational purpose","Content, calculators and assessments are informational and are not personalized investment, credit, tax, legal or insurance advice."],["Your account","Keep your credentials secure and provide lawful, accurate information. You are responsible for activity under your account."],["No guaranteed outcomes","Examples, projections and stated returns are illustrative. Financial products carry risk and results vary."],["Acceptable use","Do not misuse the service, interfere with its security or post unlawful, abusive or misleading community content."]]},
  cookies:{title:"Cookie Policy",intro:"MyFinance uses essential browser storage to keep you signed in and operate the application.",sections:[["Essential storage","Authentication tokens and interface preferences are needed for secure account access and core functionality."],["Analytics","If analytics are introduced, this policy will be updated with the provider, purpose and available controls."],["Your choices","Blocking essential storage may prevent sign-in and authenticated features from working correctly."]]}
} as const;

const Legal=()=>{const navigate=useNavigate(); const {document}=useParams(); const page=content[(document||"privacy") as keyof typeof content]||content.privacy; return <div className="min-h-screen bg-slate-50"><header className="border-b bg-white"><div className="mx-auto flex max-w-3xl items-center justify-between px-4 py-4"><strong>MyFinance</strong><Button variant="outline" onClick={()=>navigate(-1)}><ArrowLeft className="mr-2 h-4 w-4"/>Back</Button></div></header><main className="mx-auto max-w-3xl px-4 py-12"><p className="text-sm font-medium text-emerald-700">Finance Wise · Updated 10 September 2026</p><h1 className="mt-2 text-4xl font-bold">{page.title}</h1><p className="mt-5 text-lg leading-8 text-slate-600">{page.intro}</p><div className="mt-10 space-y-8">{page.sections.map(([title,text])=><section key={title}><h2 className="text-xl font-bold">{title}</h2><p className="mt-2 leading-7 text-slate-600">{text}</p></section>)}</div><p className="mt-12 border-t pt-6 text-sm text-slate-500">Questions may be sent through the contact form on the MyFinance homepage.</p></main></div>};
export default Legal;
