import { useEffect, useState } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";
import { ArrowLeft, CheckCircle2, Crown, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { useAuth } from "@/hooks/useAuth";
import { useToast } from "@/hooks/use-toast";
import { supabase } from "@/integrations/supabase/client";

const plans=[
 {name:"Free",price:"₦0",note:"forever",features:["Money Foundations course","Selected lesson previews","Financial calculators"]},
 {name:"Premium",price:"₦3,000",note:"30 days of access",popular:true,offer:"premium",features:["All 6 courses and 18 in-depth lessons","Quizzes and saved progress","Nigeria-focused investment curriculum","New premium modules as they launch"]},
 {name:"Coaching Plus",price:"₦12,500",note:"30 days of access",offer:"coaching_plus",features:["Everything in Premium","One coaching request during access period","Personal action-plan review","Priority learning support"]}
];

const Premium=()=>{const navigate=useNavigate();const [params]=useSearchParams();const {user}=useAuth();const {toast}=useToast();const [busy,setBusy]=useState<string|null>(null);
 useEffect(()=>{const reference=params.get("reference");if(params.get("payment")!=="verify"||!reference||!user)return;setBusy("verify");void supabase.functions.invoke("verify-payment",{body:{reference}}).then(({data,error})=>{setBusy(null);if(error||!data?.ok)return toast({title:"Payment is still being confirmed",description:"Please refresh shortly. Refreshing will not charge you again.",variant:"destructive"});toast({title:"Payment confirmed",description:"Your premium access is active."});navigate('/learn',{replace:true})})},[navigate,params,toast,user]);
 const checkout=async(offer:string)=>{if(!user)return navigate('/auth');setBusy(offer);const {data,error}=await supabase.functions.invoke("initialize-payment",{body:{offer}});setBusy(null);if(error||!data?.authorization_url)return toast({title:"Checkout could not start",description:data?.error||error?.message||"Please try again.",variant:"destructive"});window.location.assign(data.authorization_url)};
 return <div className="min-h-screen bg-slate-950 text-white"><header className="border-b border-white/10"><div className="mx-auto flex max-w-6xl items-center justify-between px-4 py-4"><strong>MyFinance Premium</strong><Button variant="outline" className="border-white/30 bg-transparent text-white hover:bg-white/10 hover:text-white" onClick={()=>navigate('/learn')}><ArrowLeft className="mr-2 h-4 w-4"/>Academy</Button></div></header><main><section className="mx-auto max-w-4xl px-4 py-16 text-center"><Badge className="bg-amber-400 text-slate-950"><Crown className="mr-1 h-3 w-3"/>Premium financial education</Badge><h1 className="mt-6 text-4xl font-bold md:text-6xl">A practical money curriculum built for real decisions.</h1><p className="mx-auto mt-5 max-w-2xl text-lg leading-8 text-slate-300">Go beyond tips with structured lessons, Nigeria-focused product education, risk frameworks, exercises and progress tracking.</p></section><section className="mx-auto grid max-w-6xl gap-6 px-4 pb-10 lg:grid-cols-3">{plans.map(plan=><Card key={plan.name} className={plan.popular?'border-2 border-amber-400 shadow-2xl':''}><CardHeader>{plan.popular&&<Badge className="mb-2 w-fit bg-amber-400 text-slate-950">Most popular</Badge>}<CardTitle className="text-2xl">{plan.name}</CardTitle><p><span className="text-4xl font-bold">{plan.price}</span></p><p className="text-xs text-slate-500">{plan.note}</p></CardHeader><CardContent className="space-y-5"><div className="space-y-3">{plan.features.map(x=><p key={x} className="flex gap-2 text-sm"><CheckCircle2 className="h-4 w-4 shrink-0 text-emerald-700"/>{x}</p>)}</div><Button variant={plan.popular?'default':'outline'} className={`w-full ${plan.popular?'bg-emerald-700':''}`} disabled={busy!==null} onClick={()=>plan.offer?checkout(plan.offer):navigate('/learn')}>{busy===plan.offer?'Opening secure checkout…':plan.offer?'Pay securely with Paystack':'Start learning'}</Button></CardContent></Card>)}</section><section className="mx-auto max-w-3xl px-4 pb-16"><div className="flex gap-3 rounded-xl border border-white/10 bg-white/5 p-5 text-sm leading-6 text-slate-300"><ShieldCheck className="h-6 w-6 shrink-0 text-emerald-400"/><p>Payments open on Paystack's secure checkout. This release uses test mode and cannot collect live money. Access activates only after server-side payment verification.</p></div></section></main></div>};
export default Premium;
