import { useCallback, useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { ArrowLeft, Bell, Lightbulb, Save } from "lucide-react";
import { useAuth } from "@/hooks/useAuth";
import { useToast } from "@/hooks/use-toast";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";

const tips:Record<string,string[]>={
  Budgeting:["Give every naira a purpose before the month begins.","Review transactions weekly so small leaks do not become large surprises.","Use separate categories for needs, goals and flexible spending."],
  Saving:["Automate a realistic contribution immediately after income arrives.","Build an emergency buffer before locking money into long-term products.","Increase your savings amount whenever your income rises."],
  Debt:["Pay minimums on time, then target your most expensive debt.","Compare total repayment—not only monthly instalments—before borrowing.","Never borrow money to join an investment opportunity."],
  Investing:["Verify every operator independently with the relevant regulator.","Match investment risk and access terms to your goal timeline.","Diversify gradually and never treat projected returns as guaranteed."],
  Income:["Record every income source so your plan reflects reality.","Develop skills that improve earning power before chasing high-risk returns.","Keep business and personal cash records separate."]
};
const categories=Object.keys(tips);

const Tips=()=>{const {user}=useAuth();const navigate=useNavigate();const {toast}=useToast();const [enabled,setEnabled]=useState(true);const [time,setTime]=useState("09:00");const [selected,setSelected]=useState<string[]>(["Budgeting","Saving"]);const [preferenceId,setPreferenceId]=useState<string|null>(null);
 const load=useCallback(async()=>{if(!user)return;const {data,error}=await supabase.from("daily_tips_preferences").select("id,is_enabled,notification_time,tip_categories").eq("user_id",user.id).maybeSingle();if(error)return toast({title:"Preferences could not be loaded",description:error.message,variant:"destructive"});if(data){setPreferenceId(data.id);setEnabled(data.is_enabled??true);setTime((data.notification_time||"09:00").slice(0,5));setSelected(data.tip_categories?.length?data.tip_categories:["Budgeting","Saving"])}},[toast,user]); useEffect(()=>{void load()},[load]);
 const daily=useMemo(()=>selected.flatMap(c=>tips[c]||[]).slice(0,5),[selected]); const toggle=(c:string,v:boolean)=>setSelected(cur=>v?[...new Set([...cur,c])]:cur.filter(x=>x!==c));
 const save=async()=>{if(!user)return;const payload={user_id:user.id,is_enabled:enabled,notification_time:time,tip_categories:selected,updated_at:new Date().toISOString()};const result=preferenceId?await supabase.from("daily_tips_preferences").update(payload).eq("id",preferenceId):await supabase.from("daily_tips_preferences").insert(payload).select("id").single();if(result.error)return toast({title:"Preferences not saved",description:result.error.message,variant:"destructive"});if(!preferenceId&&result.data)setPreferenceId(result.data.id);toast({title:"Tip preferences saved",description:"Your in-app tip feed is ready."})};
 return <div className="min-h-screen bg-slate-50"><header className="border-b bg-white"><div className="mx-auto flex max-w-5xl items-center justify-between px-4 py-4"><strong>MyFinance Tips</strong><Button variant="outline" onClick={()=>navigate("/dashboard")}><ArrowLeft className="mr-2 h-4 w-4"/>Dashboard</Button></div></header><main className="mx-auto grid max-w-5xl gap-6 px-4 py-10 lg:grid-cols-[1fr_1.4fr]"><Card><CardHeader><CardTitle className="flex items-center gap-2"><Bell className="h-5 w-5 text-emerald-700"/>Preferences</CardTitle><CardDescription>Choose what appears in your personalized in-app feed.</CardDescription></CardHeader><CardContent className="space-y-6"><div className="flex items-center justify-between"><Label htmlFor="tips-enabled">Enable daily tips</Label><Switch id="tips-enabled" checked={enabled} onCheckedChange={setEnabled}/></div><div className="space-y-2"><Label htmlFor="tip-time">Preferred time</Label><Input id="tip-time" type="time" value={time} onChange={e=>setTime(e.target.value)}/><p className="text-xs text-slate-500">Notification delivery will require mobile or browser permission in a later release.</p></div><div className="space-y-3"><Label>Topics</Label>{categories.map(c=><label key={c} className="flex items-center gap-3 rounded-lg border p-3"><Checkbox checked={selected.includes(c)} onCheckedChange={v=>toggle(c,v===true)}/>{c}</label>)}</div><Button className="w-full bg-emerald-700" onClick={()=>void save()}><Save className="mr-2 h-4 w-4"/>Save preferences</Button></CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2"><Lightbulb className="h-5 w-5 text-amber-600"/>Your tip feed</CardTitle><CardDescription>Practical education based on your selected topics.</CardDescription></CardHeader><CardContent className="space-y-4">{enabled&&daily.length?daily.map((tip,i)=><div key={tip} className="rounded-xl border bg-white p-4"><p className="text-xs font-bold text-emerald-700">TIP {i+1}</p><p className="mt-2 leading-7 text-slate-700">{tip}</p></div>):<div className="rounded-xl border border-dashed py-16 text-center text-slate-500">{enabled?"Select at least one topic.":"Daily tips are currently disabled."}</div>}</CardContent></Card></main></div>};
export default Tips;
