CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE public.profiles (id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE, full_name TEXT, email TEXT, phone TEXT, occupation TEXT, date_of_birth DATE, monthly_income NUMERIC CHECK (monthly_income IS NULL OR monthly_income >= 0), financial_goals TEXT[] DEFAULT ARRAY[]::TEXT[], created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE public.financial_health_assessments (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, health_score INTEGER NOT NULL CHECK (health_score BETWEEN 0 AND 100), health_category TEXT NOT NULL, assessment_data JSONB NOT NULL DEFAULT '{}'::JSONB, recommendations JSONB NOT NULL DEFAULT '{}'::JSONB, completed_at TIMESTAMPTZ DEFAULT now(), created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE public.financial_health_tips (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, health_category TEXT NOT NULL, tip_content TEXT NOT NULL, tip_source TEXT, is_personalized BOOLEAN DEFAULT false, relevance_score INTEGER, created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE public.budgets (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, name TEXT NOT NULL, total_amount NUMERIC NOT NULL CHECK (total_amount > 0), period TEXT NOT NULL DEFAULT 'monthly', start_date DATE NOT NULL, end_date DATE NOT NULL CHECK (end_date >= start_date), created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE public.budget_categories (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), budget_id UUID NOT NULL REFERENCES public.budgets(id) ON DELETE CASCADE, name TEXT NOT NULL, allocated_amount NUMERIC NOT NULL CHECK (allocated_amount >= 0), spent_amount NUMERIC DEFAULT 0 CHECK (spent_amount >= 0), created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE public.expenses (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, budget_category_id UUID REFERENCES public.budget_categories(id) ON DELETE SET NULL, amount NUMERIC NOT NULL CHECK (amount > 0), category TEXT NOT NULL, description TEXT NOT NULL, date DATE NOT NULL DEFAULT CURRENT_DATE, created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE public.savings_goals (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, name TEXT NOT NULL, description TEXT, target_amount NUMERIC NOT NULL CHECK (target_amount > 0), current_amount NUMERIC DEFAULT 0 CHECK (current_amount >= 0), target_date DATE, is_completed BOOLEAN DEFAULT false, created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE public.savings_transactions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), savings_goal_id UUID NOT NULL REFERENCES public.savings_goals(id) ON DELETE CASCADE, amount NUMERIC NOT NULL CHECK (amount > 0), transaction_type TEXT NOT NULL CHECK (transaction_type IN ('deposit', 'withdrawal')), description TEXT, date DATE NOT NULL DEFAULT CURRENT_DATE, created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE public.financial_goals (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, title TEXT NOT NULL, description TEXT, category TEXT NOT NULL, target_amount NUMERIC, current_progress NUMERIC DEFAULT 0, target_date DATE, status TEXT DEFAULT 'active', created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE public.community_posts (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, title TEXT NOT NULL, content TEXT NOT NULL, category TEXT NOT NULL, likes_count INTEGER DEFAULT 0, comments_count INTEGER DEFAULT 0, created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE public.community_comments (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), post_id UUID NOT NULL REFERENCES public.community_posts(id) ON DELETE CASCADE, user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, content TEXT NOT NULL, created_at TIMESTAMPTZ DEFAULT now());
