// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ngaxmlnthkfgnbxuwdkc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_vFLS_3_BeQIRSeQXXvdZcA_5TOKwjwZ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
