// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gzufijfkaxxklkknhmca.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd6dWZpamZrYXh4a2xra25obWNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NjMwMDgsImV4cCI6MjA2NjMzOTAwOH0.OGhsN6L8YFXQpr-kdJZ1K3zQNf_fXr3lUxlIcihxYX8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);